name: tma-backend

networks:
  app:

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    env_file:
      - api/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:8000"
    networks:
      app:
    develop:
      watch:
        - action: sync+restart
          path: ./api
          target: /app
        - action: rebuild
          path: ./poetry.lock

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - pg_db.env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      app:

volumes:
    postgres:
