# Generated by Django 5.1.6 on 2025-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("photo", models.URLField(verbose_name="Task photo")),
                ("name", models.CharField(max_length=150, verbose_name="Task name")),
                ("link", models.URLField(verbose_name="Task link")),
                ("reward", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Task reward")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("x", "X"),
                            ("instagram", "Instagram"),
                            ("youtube", "Youtube"),
                        ],
                        max_length=32,
                        verbose_name="Task type",
                    ),
                ),
            ],
        ),
    ]
