# Generated by Django 5.1.6 on 2025-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Upgrade name")),
                ("photo", models.URLField(verbose_name="Upgrade photo")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Upgrade price")),
                (
                    "boost",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=10, verbose_name="Balance per hour boost"
                    ),
                ),
            ],
        ),
    ]
