name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: installing deps
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: run tests
        run: cd api && ./manage.py test
