name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_admin
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_admin -d test_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: installing python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: installing deps
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: run tests
        env:
          BOT_TOKEN: YOUR_TOKEN
          SECRET_KEY: ab489f2bdd0e4d22e6b868145f50513e5b8492672a272ddf49b0c12c568744a3
          DEBUG: 1
          ALLOWED_HOSTS: localhost,127.0.0.1
          DB_NAME: test_db
          DB_USER: test_admin
          DB_PASSWORD: 1234
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          sleep 5
          mkdir -p api/certs
          openssl genrsa -out api/certs/jwt-private.pem 2048
          openssl rsa -in api/certs/jwt-private.pem -outform PEM -pubout -out api/certs/jwt-public.pem
          cd api && ./manage.py test
